### PR TITLE
Added max-width for content in the get in touch callout

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by rpowis** [comment]
@stevenaproctor Can you add styles to the relevant SCSS file and then generate the CSS file using the `npm start` command please?

**Comment by rpowis** [comment]
Not a very nice workflow, I know, but it means your changes won't get overridden if someone else does the same.

**Comment by ghost** [comment]
Is the relevant file _custom.scss?

And do you use npm start in this repo or assets-frontend? Sorry for the newbie questions.

**Comment by rpowis** [comment]
That's ok. I typed it in a bit hurry so I might have not been very clear. 

Yeah, it looks like `_custom.scss` is the right place: https://github.com/hmrc/component-library-template/blob/master/public/assets/stylesheets/design-system/_custom.scss#L292.  Also, you could probably just add the `max-width` to that class rather than each of its child elements.

To compile the SCSS to CSS it's just a case of running `npm start` in the root of this repo and then save the SCSS file. Then commit all the changes.

**Pull request closed without merging**
